import type { AnimationMetadata } from '@/types/animation'

export const metadata: AnimationMetadata = {
  id: 'text-effects__wave-reveal',
  urlSlugFramer: '/text-effects-framer?animation=text-effects__wave-reveal',
  urlSlugCss: '/text-effects-css?animation=text-effects__wave-reveal',
  title: 'Wave Reveal',
  description: 'Staggered wave animation where text appears from bottom with smooth easing.',
  disableReplay: false,
  tier: 3,
  props: [
    {
      type: 'string',
      name: 'line1Text',
      label: 'Line 1 Text',
      default: 'Look at',
    },
    {
      type: 'color',
      name: 'line1Color',
      label: 'Line 1 Color',
      default: 'var(--pf-anim-blue)',
    },
    {
      type: 'string',
      name: 'line2Text',
      label: 'Line 2 Text',
      default: 'these',
    },
    {
      type: 'color',
      name: 'line2Color',
      label: 'Line 2 Color',
      default: 'var(--pf-anim-green)',
    },
    {
      type: 'string',
      name: 'line3Text',
      label: 'Line 3 Text',
      default: 'colors',
    },
    {
      type: 'color',
      name: 'line3Color',
      label: 'Line 3 Color',
      default: 'var(--pf-anim-gold)',
    },
    {
      type: 'number',
      name: 'charDelay',
      label: 'Char Delay',
      default: 0.05,
      min: 0.01,
      max: 0.2,
      step: 0.01,
      unit: 's',
    },
    {
      type: 'number',
      name: 'lineDelay',
      label: 'Line Delay',
      default: 0.4,
      min: 0.1,
      max: 1,
      step: 0.05,
      unit: 's',
    },
    {
      type: 'number',
      name: 'initialDelay',
      label: 'Initial Delay',
      default: 0.2,
      min: 0,
      max: 1,
      step: 0.05,
      unit: 's',
    },
  ],
}
