import type { AnimationMetadata } from '@/types/animation'

export const metadata = {
  id: 'text-effects__floating-combat-text',
  urlSlugFramer: '/text-effects-framer?animation=text-effects__floating-combat-text',
  urlSlugCss: '/text-effects-css?animation=text-effects__floating-combat-text',
  title: 'Floating Combat Text',
  description:
    'Floating number that pops in, drifts upward, and fades out. Color determined by numeric value sign and magnitude against configurable thresholds.',
  disableReplay: false,
  tier: 2,
  demoMode: 'combat-text',
  props: [
    {
      type: 'boolean',
      name: 'randomValues',
      label: 'Random Preview',
      default: true,
      description:
        'Cycle random values across all color bands for preview. Disable to use the Value field.',
    },
    {
      type: 'string',
      name: 'value',
      label: 'Value',
      default: '-42',
      disabledWhen: { prop: 'randomValues', eq: true },
    },
    { type: 'color', name: 'colorPositiveHigh', label: 'Positive High Color', default: '#fbbf24' },
    { type: 'color', name: 'colorPositive', label: 'Positive Color', default: '#4ade80' },
    { type: 'color', name: 'colorNegative', label: 'Negative Color', default: '#f87171' },
    { type: 'color', name: 'colorNegativeHigh', label: 'Negative High Color', default: '#ef4444' },
    {
      type: 'number',
      name: 'positiveHighLimit',
      label: 'Positive High Limit',
      default: 100,
      min: 1,
      max: 10000,
      step: 10,
    },
    {
      type: 'number',
      name: 'negativeHighLimit',
      label: 'Negative High Limit',
      default: 100,
      min: 1,
      max: 10000,
      step: 10,
    },
    {
      type: 'number',
      name: 'fontSize',
      label: 'Font Size',
      default: 24,
      min: 12,
      max: 64,
      step: 2,
      unit: 'px',
    },
    {
      type: 'number',
      name: 'floatDistance',
      label: 'Float Distance',
      default: 60,
      min: 20,
      max: 150,
      step: 5,
      unit: 'px',
    },
    {
      type: 'number',
      name: 'duration',
      label: 'Duration',
      default: 800,
      min: 400,
      max: 2000,
      step: 50,
      unit: 'ms',
    },
    {
      type: 'number',
      name: 'spread',
      label: 'Spread',
      default: 20,
      min: 0,
      max: 60,
      step: 5,
      unit: 'px',
    },
    { type: 'string', name: 'fontFamily', label: 'Font Family', default: 'inherit' },
    { type: 'string', name: 'fontWeight', label: 'Font Weight', default: '700' },
    {
      type: 'string',
      name: 'onComplete',
      label: 'On Complete',
      disabled: true,
      disabledReason: 'Callback — set in code',
    },
  ],
} satisfies AnimationMetadata
