import type { AnimationMetadata } from '@/types/animation'

export const metadata: AnimationMetadata = {
  id: 'icon-animations__tap-arrow',
  urlSlugFramer: '/icon-animations-framer?animation=icon-animations__tap-arrow',
  urlSlugCss: '/icon-animations-css?animation=icon-animations__tap-arrow',
  title: 'Tap Arrow',
  description:
    'Floating pointer arrow that bobs toward a center element. Classic mobile-game "tap here" indicator. Props: position, arrowSrc, fill, stroke, strokeWidth, duration, nudgeDistance, arrowSize.',
  tier: 2,
  order: 100,
  props: [
    {
      type: 'select',
      name: 'position',
      label: 'Arrow Position',
      description: 'Which side the arrow appears on.',
      default: 'left',
      options: [
        { label: 'Left', value: 'left' },
        { label: 'Right', value: 'right' },
        { label: 'Top', value: 'top' },
        { label: 'Bottom', value: 'bottom' },
      ],
    },
    {
      type: 'image',
      name: 'arrowSrc',
      label: 'Arrow Image',
      description: 'Custom arrow image URL. When set, fill/stroke props are ignored.',
    },
    {
      type: 'color',
      name: 'fill',
      label: 'Fill Color',
      description: 'SVG fill color (default arrow only).',
      default: '#c83558',
    },
    {
      type: 'color',
      name: 'stroke',
      label: 'Stroke Color',
      description: 'SVG stroke color (default arrow only).',
      default: '#000000',
    },
    {
      type: 'number',
      name: 'strokeWidth',
      label: 'Stroke Width',
      description: 'SVG stroke width (default arrow only).',
      default: 0,
      min: 0,
      max: 10,
      step: 0.5,
      unit: 'px',
    },
    {
      type: 'number',
      name: 'duration',
      label: 'Duration',
      default: 1200,
      min: 400,
      max: 4000,
      step: 100,
      unit: 'ms',
    },
    {
      type: 'number',
      name: 'nudgeDistance',
      label: 'Nudge Distance',
      description: 'How far the arrow nudges toward the target.',
      default: 12,
      min: 2,
      max: 40,
      step: 2,
      unit: 'px',
    },
    {
      type: 'number',
      name: 'arrowSize',
      label: 'Arrow Size',
      default: 48,
      min: 16,
      max: 120,
      step: 4,
      unit: 'px',
    },
  ],
}
