import type { AnimationMetadata } from '@/types/animation'

export const metadata = {
  id: 'timer-effects__timer-pulse',
  urlSlugFramer: '/timer-effects-framer?animation=timer-effects__timer-pulse',
  urlSlugCss: '/timer-effects-css?animation=timer-effects__timer-pulse',
  title: 'Timer Pulse',
  description: 'Large countdown number with pulse animation and depleting underline bar.',
  tier: 4,
  props: [
    {
      type: 'number',
      name: 'startSeconds',
      label: 'Start Seconds',
      default: 10,
      min: 5,
      max: 120,
      step: 1,
      unit: 's',
    },
    {
      type: 'select',
      name: 'mode',
      label: 'Mode',
      default: 'visual',
      options: [
        { label: 'Visual', value: 'visual' },
        { label: 'Exact', value: 'exact' },
      ],
    },
    {
      type: 'color',
      name: 'normalTextColor',
      label: 'Normal Color',
      default: '#ecc3ff',
      description: 'Number color when plenty of time remains.',
    },
    {
      type: 'color',
      name: 'warningTextColor',
      label: 'Warning Color',
      default: '#ffb347',
      description: 'Number color when time is getting low.',
    },
    {
      type: 'color',
      name: 'criticalTextColor',
      label: 'Critical Color',
      default: '#ff6b6b',
      description: 'Number color in the final seconds.',
    },
    {
      type: 'number',
      name: 'warningThreshold',
      label: 'Warning At',
      default: 6,
      min: 1,
      max: 120,
      step: 1,
      unit: 's',
      description: 'Seconds remaining to enter warning phase.',
    },
    {
      type: 'number',
      name: 'criticalThreshold',
      label: 'Critical At',
      default: 3,
      min: 1,
      max: 60,
      step: 1,
      unit: 's',
      description: 'Seconds remaining to enter critical phase.',
    },
    {
      type: 'string',
      name: 'onEnd',
      label: 'On End',
      disabled: true,
      disabledReason: 'Callback — set via code',
    },
    {
      type: 'select',
      name: 'onEndBehavior',
      label: 'On End Behavior',
      default: 'stay',
      options: [
        { label: 'Hide', value: 'hide' },
        { label: 'Stay', value: 'stay' },
      ],
    },
    {
      type: 'color',
      name: 'barColor',
      label: 'Bar Color',
      description: 'Color of the progress underline bar.',
    },
    {
      type: 'number',
      name: 'fontSize',
      label: 'Font Size',
      default: 40,
      min: 8,
      max: 72,
      step: 1,
      unit: 'px',
    },
    { type: 'boolean', name: 'showUnderline', label: 'Show Underline', default: true },
  ],
} satisfies AnimationMetadata
