import type { AnimationMetadata } from '@/types/animation'

export const metadata: AnimationMetadata = {
  id: 'timer-effects__countdown-burst',
  urlSlugFramer: '/timer-effects-framer?animation=timer-effects__countdown-burst',
  urlSlugCss: '/timer-effects-css?animation=timer-effects__countdown-burst',
  title: 'Countdown Burst',
  description:
    'Dramatic 3-2-1-GO! countdown with expanding ring, pulsing glow, and radial particle burst on each step.',
  tier: 3,
  disableReplay: false,
  props: [
    {
      type: 'number',
      name: 'count',
      label: 'Count From',
      default: 3,
      min: 0,
      max: 10,
      step: 1,
    },
    {
      type: 'string',
      name: 'goText',
      label: 'Go Text',
      default: 'GO!',
    },
    {
      type: 'number',
      name: 'stepDuration',
      label: 'Step Duration',
      default: 800,
      min: 300,
      max: 2000,
      step: 50,
      unit: 'ms',
    },
    {
      type: 'number',
      name: 'goDuration',
      label: 'Go Hold Duration',
      default: 700,
      min: 200,
      max: 2000,
      step: 50,
      unit: 'ms',
    },
    {
      type: 'color',
      name: 'countdownColor',
      label: 'Countdown Color',
      default: '#ecc3ff',
      description: 'Color of the text, ring, glow, and particles during numbered steps.',
    },
    {
      type: 'color',
      name: 'goColor',
      label: 'Go Color',
      default: '#4db88a',
      description: 'Color of the text, ring, glow, and particles on the GO step.',
    },
    {
      type: 'number',
      name: 'particleCount',
      label: 'Particles',
      default: 8,
      min: 0,
      max: 24,
      step: 1,
    },
    {
      type: 'number',
      name: 'size',
      label: 'Size',
      default: 200,
      min: 80,
      max: 400,
      step: 10,
      unit: 'px',
    },
    {
      type: 'string',
      name: 'fontSize',
      label: 'Font Size',
      default: '5rem',
    },
    {
      type: 'string',
      name: 'onComplete',
      label: 'On Complete',
      disabled: true,
      disabledReason: 'Callback — set via code',
    },
    {
      type: 'string',
      name: 'onStep',
      label: 'On Step',
      disabled: true,
      disabledReason: 'Callback — set via code',
    },
  ],
}
