import type { AnimationMetadata } from '@/types/animation'

export const metadata = {
  id: 'timer-effects__urgent-pulse',
  urlSlugFramer: '/timer-effects-framer?animation=timer-effects__urgent-pulse',
  urlSlugCss: '/timer-effects-css?animation=timer-effects__urgent-pulse',
  title: 'Urgent Pulse',
  description:
    'Urgent pulsing countdown with gradient shift. Configurable: startSeconds, mode, colors, thresholds, onEnd, onEndBehavior.',
  tier: 4,
  props: [
    {
      type: 'number',
      name: 'startSeconds',
      label: 'Start Seconds',
      default: 5,
      min: 5,
      max: 120,
      step: 1,
      unit: 's',
    },
    {
      type: 'select',
      name: 'mode',
      label: 'Mode',
      default: 'visual',
      options: [
        { label: 'Visual', value: 'visual' },
        { label: 'Exact', value: 'exact' },
      ],
    },
    {
      type: 'color',
      name: 'normalColor', group: 'normal-phase',
      label: 'Normal BG',
      default: '#ffb300',
    },
    { type: 'color', name: 'normalTextColor', group: 'normal-phase', label: 'Normal Text', description: 'Colors for the normal phase.' },
    {
      type: 'color',
      name: 'warningColor', group: 'warning-phase',
      label: 'Warning BG',
      default: '#ff7a00',
    },
    { type: 'color', name: 'warningTextColor', group: 'warning-phase', label: 'Warning Text', description: 'Colors for the warning phase.' },
    {
      type: 'color',
      name: 'criticalColor', group: 'critical-phase',
      label: 'Critical BG',
      default: '#dc3545',
    },
    { type: 'color', name: 'criticalTextColor', group: 'critical-phase', label: 'Critical Text', description: 'Colors for the critical phase.' },
    {
      type: 'number',
      name: 'warningThreshold',
      label: 'Warning At',
      default: 3,
      min: 1,
      max: 120,
      step: 1,
      unit: 's',
      description: 'Seconds remaining to enter warning phase.',
    },
    {
      type: 'number',
      name: 'criticalThreshold',
      label: 'Critical At',
      default: 1,
      min: 1,
      max: 60,
      step: 1,
      unit: 's',
      description: 'Seconds remaining to enter critical phase.',
    },
    { type: 'string',
      name: 'onEnd',
      label: 'On End',
      disabled: true,
      disabledReason: 'Callback — set via code',
    },
    {
      type: 'select',
      name: 'onEndBehavior',
      label: 'On End Behavior',
      default: 'stay',
      options: [
        { label: 'Hide', value: 'hide' },
        { label: 'Stay', value: 'stay' },
      ],
    },
    { type: 'number', name: 'fontSize', label: 'Font Size', default: 16, min: 8, max: 48, step: 1, unit: 'px' },
  ],
} satisfies AnimationMetadata
