import type { AnimationMetadata } from '@/types/animation'

export const metadata = {
  id: 'celebration-effects__treasure-particles',
  urlSlugFramer: '/celebration-effects-framer?animation=celebration-effects__treasure-particles',
  urlSlugCss: '/celebration-effects-css?animation=celebration-effects__treasure-particles',
  title: 'Treasure Eruption',
  description:
    'Mixed coins and gems erupt radially with parabolic gravity. Configurable coinCount, gemCount, coinImage, colors, duration, and onComplete callback.',
  tier: 4,
  props: [
    {
      type: 'number',
      name: 'coinCount',
      label: 'Coin Count',
      default: 12,
      min: 1,
      max: 40,
      step: 1,
    },
    { type: 'number', name: 'gemCount', label: 'Gem Count', default: 12, min: 1, max: 40, step: 1 },
    { type: 'image', name: 'coinImage', label: 'Coin Image' },
    {
      type: 'number',
      name: 'duration',
      label: 'Duration',
      default: 2000,
      min: 600,
      max: 5000,
      step: 100,
      unit: 'ms',
    },
    {
      type: 'colors',
      name: 'colors',
      label: 'Colors',
      default: ['#ffd700', '#d97706', '#fde68a', '#fbbf24', '#ffc107'],
      maxItems: 8,
    },
    { type: 'images', name: 'particleImages', label: 'Particle Images', default: [], maxItems: 10 },
    {
      type: 'number',
      name: 'particleMaxWidth',
      label: 'Max Particle Width',
      default: 24,
      min: 8,
      max: 80,
      step: 2,
      unit: 'px',
    },
    {
      type: 'number',
      name: 'particleMaxHeight',
      label: 'Max Particle Height',
      default: 24,
      min: 8,
      max: 80,
      step: 2,
      unit: 'px',
    },
    {
      type: 'string',
      name: 'onComplete',
      label: 'On Complete',
      disabled: true,
      disabledReason: 'Callback — set in code',
    },
  ],
} satisfies AnimationMetadata
