import type { AnimationMetadata } from '@/types/animation'

export const metadata = {
  id: 'text-effects__floating-combat-text',
  urlSlugFramer: '/text-effects-framer?animation=text-effects__floating-combat-text',
  urlSlugCss: '/text-effects-css?animation=text-effects__floating-combat-text',
  title: 'Floating Combat Text',
  description:
    'Damage/heal/gold number that pops in, drifts upward with random horizontal spread, and fades out. Spawn multiple instances for overlapping combat numbers.',
  disableReplay: false,
  tier: 2,
  demoMode: 'combat-text',
  props: [
    { type: 'string', name: 'value', label: 'Value', default: '-42' },
    {
      type: 'select',
      name: 'type',
      label: 'Type',
      default: 'damage',
      options: [
        { label: 'Damage', value: 'damage' },
        { label: 'Heal', value: 'heal' },
        { label: 'Gold', value: 'gold' },
        { label: 'Neutral', value: 'neutral' },
        { label: 'Critical', value: 'critical' },
      ],
    },
    { type: 'color', name: 'color', label: 'Color Override' },
    {
      type: 'number',
      name: 'fontSize',
      label: 'Font Size',
      default: 24,
      min: 12,
      max: 64,
      step: 2,
      unit: 'px',
    },
    {
      type: 'number',
      name: 'floatDistance',
      label: 'Float Distance',
      default: 60,
      min: 20,
      max: 150,
      step: 5,
      unit: 'px',
    },
    {
      type: 'number',
      name: 'duration',
      label: 'Duration',
      default: 800,
      min: 400,
      max: 2000,
      step: 50,
      unit: 'ms',
    },
    {
      type: 'number',
      name: 'spread',
      label: 'Spread',
      default: 20,
      min: 0,
      max: 60,
      step: 5,
      unit: 'px',
    },
    { type: 'string', name: 'fontFamily', label: 'Font Family', default: 'inherit' },
    { type: 'string', name: 'fontWeight', label: 'Font Weight', default: '700' },
    {
      type: 'string',
      name: 'onComplete',
      label: 'On Complete',
      disabled: true,
      disabledReason: 'Callback — set in code',
    },
  ],
} satisfies AnimationMetadata
