import type { AnimationMetadata } from '@/types/animation'

export const metadata = {
  id: 'collection-effects__coin-magnet',
  urlSlugFramer: '/collection-effects-framer?animation=collection-effects__coin-magnet',
  urlSlugCss: '/collection-effects-css?animation=collection-effects__coin-magnet',
  title: 'Coin Magnet',
  description:
    'Particles fly along parabolic arcs from a source area to a target point with overshoot settle. Configurable from/to, particle images or color palette, count, spread, duration, and onComplete callback.',
  tier: 3,
  demoMode: 'magnet',
  props: [
    {
      type: 'number',
      name: 'count',
      label: 'Particle Count',
      default: 10,
      min: 1,
      max: 40,
      step: 1,
    },
    {
      type: 'number',
      name: 'particleSize',
      label: 'Particle Size',
      default: 24,
      min: 8,
      max: 80,
      step: 2,
      unit: 'px',
    },
    {
      type: 'number',
      name: 'spread',
      label: 'Emit Distance',
      default: 60,
      min: 10,
      max: 200,
      step: 10,
      unit: 'px',
    },
    {
      type: 'number',
      name: 'duration',
      label: 'Duration',
      default: 1333,
      min: 300,
      max: 5000,
      step: 100,
      unit: 'ms',
    },
    {
      type: 'images',
      name: 'particleImages',
      label: 'Particle Images',
      default: ['/images/coin-particle.png'],
      maxItems: 10,
    },
    {
      type: 'colors',
      name: 'colors',
      label: 'Fallback Colors',
      default: ['#FFD700', '#FF6B6B', '#4ECDC4'],
      maxItems: 8,
    },
    {
      type: 'string',
      name: 'from',
      label: 'From Point',
      disabled: true,
      disabledReason: 'Ref or {x,y} — set in code',
    },
    {
      type: 'string',
      name: 'to',
      label: 'To Point',
      disabled: true,
      disabledReason: 'Ref or {x,y} — set in code',
    },
    {
      type: 'string',
      name: 'onComplete',
      label: 'On Complete',
      disabled: true,
      disabledReason: 'Callback — set in code',
    },
  ],
} satisfies AnimationMetadata
