import type { AnimationMetadata } from '@/types/animation'

export const metadata = {
  id: 'collection-effects__coin-trail',
  urlSlugFramer: '/collection-effects-framer?animation=collection-effects__coin-trail',
  urlSlugCss: '/collection-effects-css?animation=collection-effects__coin-trail',
  title: 'Coin Trail',
  description:
    'Particles arc along a smooth bezier curve from source to target. Each particle follows a slightly different path for organic feel. Configurable from/to, spread (arc height), particle images or colors, count, duration, and onComplete.',
  tier: 3,
  tags: [],
  order: -1,
  demoMode: 'trail',
  props: [
    {
      type: 'number',
      name: 'count',
      label: 'Particle Count',
      default: 8,
      min: 1,
      max: 40,
      step: 1,
    },
    {
      type: 'number',
      name: 'particleSize',
      label: 'Particle Size',
      default: 24,
      min: 8,
      max: 80,
      step: 2,
      unit: 'px',
    },
    {
      type: 'number',
      name: 'spread',
      label: 'Pop-up Height',
      default: 50,
      min: 10,
      max: 200,
      step: 10,
      unit: 'px',
    },
    {
      type: 'number',
      name: 'duration',
      label: 'Duration',
      default: 1000,
      min: 300,
      max: 5000,
      step: 100,
      unit: 'ms',
    },
    {
      type: 'images',
      name: 'particleImages',
      label: 'Particle Images',
      default: ['/images/coin-particle.png'],
      maxItems: 10,
    },
    {
      type: 'colors',
      name: 'colors',
      label: 'Fallback Colors',
      default: ['#FFD700', '#FF6B6B', '#4ECDC4'],
      maxItems: 8,
    },
    {
      type: 'string',
      name: 'from',
      label: 'From Point',
      disabled: true,
      disabledReason: 'Ref or {x,y} — set in code',
    },
    {
      type: 'string',
      name: 'to',
      label: 'To Point',
      disabled: true,
      disabledReason: 'Ref or {x,y} — set in code',
    },
    {
      type: 'string',
      name: 'onComplete',
      label: 'On Complete',
      disabled: true,
      disabledReason: 'Callback — set in code',
    },
  ],
} satisfies AnimationMetadata
