/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_APP_TITLE?: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}

/** Virtual module generated by vite/plugins/animationTitleIndexPlugin. */
declare module 'virtual:animation-title-index' {
  export const groupTitles: Record<string, { id: string; title: string }[]>
}
