import { Button } from '@/demo-ui/components/ui/Button'
import { Modal } from '@/demo-ui/components/ui/Modal'
import { Tabs, type Tab } from '@/demo-ui/components/ui/Tabs'
import { highlightCode } from '@/lib/highlighter'
import { logger } from '@/services/logger'
import { cleanSourceForDisplay } from '@/lib/sourceTransform'
import type { SourceTab } from '@/types/animation'
import { CopyCheckIcon, CopyIcon } from '@/components/ui/icons'
import { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import './CodeViewerModal.css'

/** Props for the CodeViewerModal component. */
interface CodeViewerModalProps {
  sources: SourceTab[]
  title: string
  onClose: () => void
}

function stripShikiBackground(html: string): string {
  return html
    .replace(/background-color:[^;"]+;?/g, 'background-color: transparent;')
    .replace(/background:[^;"]+;?/g, 'background: transparent;')
}

/** Escapes raw source for safe HTML rendering when syntax highlighting is unavailable. */
function escapeHtmlForFallback(code: string): string {
  return `<pre><code>${code
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')}</code></pre>`
}

/** Highlights all source tabs and tracks loading state. */
function useHighlightedSources(sources: SourceTab[]) {
  const [highlighted, setHighlighted] = useState<string[]>([])
  const [loading, setLoading] = useState(true)

  const sourceKey = useMemo(() => sources.map((s) => s.code).join('\0'), [sources])
  const sourcesRef = useRef(sources)
  sourcesRef.current = sources

  useEffect(() => {
    let cancelled = false
    async function run() {
      // Reset to loading on every effect run so a `sources` swap doesn't leave
      // the body rendering stale highlighted HTML with `loading=false`.
      setLoading(true)
      const cleanedSources = sourcesRef.current.map((tab) => ({
        ...tab,
        cleaned: cleanSourceForDisplay(tab.code),
      }))
      try {
        const results = await Promise.all(
          cleanedSources.map((tab) =>
            highlightCode(tab.cleaned, tab.language).then(stripShikiBackground)
          )
        )
        if (!cancelled) {
          setHighlighted(results)
          setLoading(false)
        }
      } catch (err) {
        // Shiki failed to load (network error, cached rejection from a prior
        // failure). Without this guard, loading stays true forever and the
        // modal is stuck. Fall back to escaped raw source — readable, just
        // unhighlighted — and drop the loading state so the user sees code.
        if (cancelled) return
        logger.warn('Code viewer: syntax highlighting unavailable — showing raw source', err)
        setHighlighted(cleanedSources.map((tab) => escapeHtmlForFallback(tab.cleaned)))
        setLoading(false)
      }
    }
    run()
    return () => {
      cancelled = true
    }
  }, [sourceKey])

  return { highlighted, loading }
}

/** Manages active file selection and clipboard copy. */
function useFileSelection(sources: SourceTab[]) {
  const [activeId, setActiveId] = useState(sources[0]?.label ?? '')
  const [copied, setCopied] = useState(false)
  const copyTimerRef = useRef<ReturnType<typeof setTimeout>>(undefined)

  useEffect(() => () => clearTimeout(copyTimerRef.current), [])

  const activeIndex = sources.findIndex((s) => s.label === activeId)
  const safeIndex = activeIndex >= 0 ? activeIndex : 0

  const handleCopy = useCallback(async () => {
    try {
      const activeSource = sources[safeIndex]
      await navigator.clipboard.writeText(
        activeSource ? cleanSourceForDisplay(activeSource.code) : ''
      )
      setCopied(true)
      clearTimeout(copyTimerRef.current)
      copyTimerRef.current = setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      logger.warn('Clipboard write failed — browser may have denied access', err)
    }
  }, [safeIndex, sources])

  return { activeId, setActiveId, safeIndex, copied, handleCopy }
}

/** Renders Shiki-highlighted HTML. Output is trusted (generated by Shiki, not user input). */
function HighlightedCode({ html }: { html: string }) {
  // eslint-disable-next-line @eslint-react/dom/no-dangerously-set-innerhtml -- Shiki output is trusted
  return <div data-testid="code-highlighted" dangerouslySetInnerHTML={{ __html: html }} />
}

/** Code viewer modal: Modal shell + Tabs (one tab per source file). */
function CodeViewerModalComponent({ sources, title, onClose }: CodeViewerModalProps) {
  const { highlighted, loading } = useHighlightedSources(sources)
  const selection = useFileSelection(sources)

  const tabs: Tab[] = useMemo(
    () =>
      sources.map((source, i) => ({
        id: source.label,
        label: source.label,
        content: loading ? (
          <div className="code-modal__loading" data-testid="code-loading">
            Loading syntax highlighting...
          </div>
        ) : (
          <div className="code-modal__body" data-testid="code-body">
            <HighlightedCode html={highlighted[i] ?? ''} />
          </div>
        ),
      })),
    [sources, highlighted, loading]
  )

  const copyButton = (
    <Button
      variant="ghost"
      size="sm"
      onClick={selection.handleCopy}
      data-testid="code-copy-btn"
      className={`gap-1 ${selection.copied ? 'text-[var(--theme-accent)]' : ''}`}
    >
      {selection.copied ? (
        <>
          <CopyCheckIcon /> Copied
        </>
      ) : (
        <>
          <CopyIcon /> Copy
        </>
      )}
    </Button>
  )

  return (
    <Modal
      isOpen
      onClose={onClose}
      title={title}
      headerRight={copyButton}
      width="max-w-3xl"
      bodyClassName="flex flex-col max-h-[70vh] overflow-hidden p-0"
      data-testid="code-viewer-modal"
    >
      <Tabs
        tabs={tabs}
        value={selection.activeId}
        onChange={selection.setActiveId}
        className="flex-1 min-h-0 flex flex-col"
        tabListClassName="px-2 bg-panel-header/50"
        contentClassName="flex-1 overflow-y-auto code-modal__content"
        data-testid="code-tablist"
      />
    </Modal>
  )
}

export const CodeViewerModal = memo(CodeViewerModalComponent)
