import { highlightCode } from '@/lib/highlighter'
import { logger } from '@/services/logger'
import { cleanSourceForDisplay } from '@/lib/sourceTransform'
import type { SourceTab } from '@/types/animation'
import { CloseIcon } from '@/components/ui/icons/CloseIcon'
import { CopyCheckIcon, CopyIcon } from '@/components/ui/icons/CopyIcon'
import { useEscapeClose, useFocusTrap, useOverlayDismiss } from '@/hooks/useModalAccessibility'
import { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import './CodeViewerModal.css'

interface CodeViewerModalProps {
  sources: SourceTab[]
  title: string
  onClose: () => void
}

// ── Hooks ──────────────────────────────────────────────────────────────

function useHighlightedSources(sources: SourceTab[]) {
  const [highlighted, setHighlighted] = useState<string[]>([])
  const [loading, setLoading] = useState(true)

  // Stable key to avoid re-highlighting on every render
  const sourceKey = useMemo(() => sources.map((s) => s.code).join('\0'), [sources])

  useEffect(() => {
    let cancelled = false

    async function run() {
      const results = await Promise.all(
        sources.map((tab) => highlightCode(cleanSourceForDisplay(tab.code), tab.language))
      )
      if (!cancelled) {
        setHighlighted(results)
        setLoading(false)
      }
    }

    run()
    return () => {
      cancelled = true
    }
  }, [sourceKey]) // eslint-disable-line @eslint-react/exhaustive-deps -- sourceKey is the stable identity derived from sources

  return { highlighted, loading }
}

function useFileSelection(sources: SourceTab[]) {
  const [activeIndex, setActiveIndex] = useState(0)
  const [copied, setCopied] = useState(false)

  const copyTimerRef = useRef<ReturnType<typeof setTimeout>>(undefined)
  useEffect(() => () => clearTimeout(copyTimerRef.current), [])

  const handleCopy = useCallback(async () => {
    try {
      const activeSource = sources[activeIndex]
      await navigator.clipboard.writeText(
        activeSource ? cleanSourceForDisplay(activeSource.code) : ''
      )
      setCopied(true)
      clearTimeout(copyTimerRef.current)
      copyTimerRef.current = setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      logger.warn('Clipboard write failed — browser may have denied access', err)
    }
  }, [activeIndex, sources])

  return { activeIndex, setActiveIndex, copied, handleCopy }
}

// ── Sub-components ─────────────────────────────────────────────────────

/** Renders Shiki-highlighted HTML. Output is trusted (generated by Shiki, not user input). */
function HighlightedCode({ html }: { html: string }) {
  // eslint-disable-next-line @eslint-react/dom/no-dangerously-set-innerhtml -- Shiki output is trusted
  return <div data-testid="code-highlighted" dangerouslySetInnerHTML={{ __html: html }} />
}

function TabBar({
  sources,
  activeIndex,
  onSelect,
}: {
  sources: SourceTab[]
  activeIndex: number
  onSelect: (index: number) => void
}) {
  const tabListRef = useRef<(HTMLButtonElement | null)[]>([])

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      let next = activeIndex

      if (e.key === 'ArrowRight') {
        next = (activeIndex + 1) % sources.length
      } else if (e.key === 'ArrowLeft') {
        next = (activeIndex - 1 + sources.length) % sources.length
      } else if (e.key === 'Home') {
        next = 0
      } else if (e.key === 'End') {
        next = sources.length - 1
      } else {
        return
      }

      e.preventDefault()
      onSelect(next)
      tabListRef.current[next]?.focus()
    },
    [activeIndex, sources.length, onSelect]
  )

  return (
    <div
      className="code-modal__tablist"
      role="tablist"
      aria-label="Source files"
      data-testid="code-tablist"
    >
      {sources.map((source, i) => {
        const isActive = i === activeIndex
        return (
          <button
            key={source.label}
            ref={(el) => {
              tabListRef.current[i] = el
            }}
            role="tab"
            type="button"
            className={`code-modal__tab ${isActive ? 'code-modal__tab--active' : ''}`}
            aria-selected={isActive}
            tabIndex={isActive ? 0 : -1}
            onClick={() => onSelect(i)}
            onKeyDown={handleKeyDown}
            data-testid={`code-tab-${i}`}
          >
            {source.label}
          </button>
        )
      })}
    </div>
  )
}

function ModalHeader({
  sources,
  activeIndex,
  onSelect,
  copied,
  onCopy,
  onClose,
  closeButtonRef,
}: {
  sources: SourceTab[]
  activeIndex: number
  onSelect: (index: number) => void
  copied: boolean
  onCopy: () => void
  onClose: () => void
  closeButtonRef: React.RefObject<HTMLButtonElement | null>
}) {
  return (
    <div className="code-modal__header">
      <TabBar sources={sources} activeIndex={activeIndex} onSelect={onSelect} />
      <div className="code-modal__actions">
        <button
          type="button"
          className={`code-modal__copy ${copied ? 'code-modal__copy--done' : ''}`}
          onClick={onCopy}
          data-testid="code-copy-btn"
        >
          {copied ? (
            <>
              <CopyCheckIcon /> Copied
            </>
          ) : (
            <>
              <CopyIcon /> Copy
            </>
          )}
        </button>
        <button
          type="button"
          className="code-modal__close"
          onClick={onClose}
          ref={closeButtonRef}
          aria-label="Close code viewer"
          data-testid="code-close-btn"
        >
          <CloseIcon />
        </button>
      </div>
    </div>
  )
}

// ── Main component ─────────────────────────────────────────────────────

function CodeViewerModalComponent({ sources, title, onClose }: CodeViewerModalProps) {
  const overlayRef = useRef<HTMLDivElement>(null)
  const modalRef = useRef<HTMLDivElement>(null)
  const closeButtonRef = useRef<HTMLButtonElement>(null)

  const selection = useFileSelection(sources)
  const { highlighted, loading } = useHighlightedSources(sources)
  useFocusTrap(modalRef, closeButtonRef)
  useEscapeClose(onClose)
  const handleOverlayClick = useOverlayDismiss(overlayRef, onClose)

  return (
    <div
      className="code-modal-overlay"
      ref={overlayRef}
      onClick={handleOverlayClick}
      role="dialog"
      aria-modal="true"
      aria-label={`Source code for ${title}`}
      data-testid="code-viewer-modal"
    >
      <div className="code-modal" ref={modalRef}>
        <ModalHeader
          sources={sources}
          activeIndex={selection.activeIndex}
          onSelect={selection.setActiveIndex}
          copied={selection.copied}
          onCopy={selection.handleCopy}
          onClose={onClose}
          closeButtonRef={closeButtonRef}
        />
        <div
          className="code-modal__body"
          role="tabpanel"
          aria-label={sources[selection.activeIndex]?.label}
          data-testid="code-body"
        >
          {loading ? (
            <div className="code-modal__loading" data-testid="code-loading">
              Loading syntax highlighting...
            </div>
          ) : (
            <HighlightedCode html={highlighted[selection.activeIndex] ?? ''} />
          )}
        </div>
      </div>
    </div>
  )
}

export const CodeViewerModal = memo(CodeViewerModalComponent)
